Repository lambdaclass/zksync-era, pull requests merged in 2024-02, with the labels that each got.

#85 fix: tests using the new env var
  core/tests/ts-integration/src/helpers.ts
  core/tests/ts-integration/tests/contracts.test.ts
  core/tests/ts-integration/tests/system.test.ts
Labels: external-contribution, validium

#87 Validium fix test new env value
  core/tests/ts-integration/src/helpers.ts
  core/tests/ts-integration/tests/contracts.test.ts
  core/tests/ts-integration/tests/system.test.ts
Labels: external-contribution

#91 fix: hardhat error
  hardhat.config.ts
Labels: external-contribution

#94 feat: Abstract commit data generator initialization
  core/lib/config/src/configs/chain.rs
  core/lib/env_config/src/chain.rs
  core/lib/zksync_core/src/lib.rs
  etc/env/base/chain.toml
Labels: external-contribution, validium

#92 feat: Rename Validium abstraction and implementors
  core/bin/external_node/src/main.rs
  core/lib/config/src/configs/chain.rs
  core/lib/env_config/src/chain.rs
  core/lib/types/src/aggregated_operations.rs
  core/lib/types/src/l1_batch_commit_data_generator.rs
  core/lib/types/src/lib.rs
  core/lib/zksync_core/src/consistency_checker/mod.rs
  core/lib/zksync_core/src/consistency_checker/tests/mod.rs
  core/lib/zksync_core/src/eth_sender/aggregator.rs
  core/lib/zksync_core/src/eth_sender/publish_criterion.rs
  core/lib/zksync_core/src/eth_sender/tests.rs
  core/lib/zksync_core/src/lib.rs
  etc/env/base/chain.toml
Labels: external-contribution, validium

#52 test: Native erc20 deposit integration tests
  core/tests/ts-integration/tests/deposit.test.ts
Labels: external-contribution

#95 fix: rollup
  core/tests/ts-integration/src/helpers.ts
  etc/env/base/chain.toml
  etc/env/base/eth_sender.toml
  infrastructure/zk/src/init.ts
Labels: external-contribution, validium

#98 feat: Not charging for pubdata
  core/lib/config/src/configs/eth_sender.rs
  core/lib/env_config/src/eth_sender.rs
  core/lib/zksync_core/src/fee_model.rs
  core/lib/zksync_core/src/l1_gas_price/gas_adjuster/mod.rs
  core/lib/zksync_core/src/l1_gas_price/gas_adjuster/tests.rs
  core/lib/zksync_core/src/state_keeper/io/tests/tester.rs
  etc/env/base/eth_sender.toml
Labels: external-contribution, validium

#99 Fix some comments
  etc/env/base/chain.toml
  etc/env/base/eth_sender.toml
  infrastructure/zk/src/init.ts
Labels: external-contribution, validium

#103 fix: missing structure fields in 'testonly.rs'
  core/lib/config/src/testonly.rs
Labels: external-contribution, validium

#114 fix: test new vars
  infrastructure/zk/src/constants.ts
  infrastructure/zk/src/init.ts
Labels: external-contribution

#122 fix: exclude validium_mode_example from .dockerignore
  .dockerignore
Labels: external-contribution

#136 feat: Match ABI encoding adding `bytes pubdata` at the end of the encoding in Validium's commit data
  core/lib/types/src/l1_batch_commit_data_generator.rs
Labels: external-contribution, validium

#121 feat: adapt `consistency_checker` tests for running both in Validium mode and Rollup mode
  core/lib/types/src/l1_batch_commit_data_generator.rs
  core/lib/zksync_core/src/consistency_checker/tests/mod.rs
  core/lib/zksync_core/src/consistency_checker/tests/test_helpers.rs
Labels: external-contribution, validium, testing

#137 fix: update function visibility in `consistency_checker` tests
  core/lib/zksync_core/src/consistency_checker/tests/mod.rs
  core/lib/zksync_core/src/consistency_checker/tests/test_helpers.rs
Labels: external-contribution

#138 feat: `--validium-mode` flag sets Validium config automatically
  infrastructure/zk/src/constants.ts
  infrastructure/zk/src/init.ts
Labels: external-contribution, validium

#120 feat: adapt `eth_sender` tests for running both in Validium mode and Rollup mode
  core/lib/zksync_core/src/eth_sender/mod.rs
  core/lib/zksync_core/src/eth_sender/tests.rs
  core/lib/zksync_core/src/eth_sender/tests_helpers.rs
Labels: external-contribution, validium

#142 feat: adapt `zksync_env_config::eth_sender` tests for running both in Validium mode and Rollup mode
  core/lib/env_config/src/eth_sender.rs
Labels: external-contribution, validium

#143 feat: adapt `zksync_env_config::chain` tests for running both in Validium mode and Rollup mode
  core/lib/env_config/src/chain.rs
Labels: external-contribution, validium, testing

#116 Fix withdraw tests
  core/tests/ts-integration/tests/withdraw.test.ts
Labels: erc20-base-token

#152 Add `l1_batch_commit_data_generator` as parameter to the `ConsistencyChecker` structure
  core/bin/external_node/src/main.rs
  core/lib/zksync_core/src/consistency_checker/mod.rs
  core/lib/zksync_core/src/consistency_checker/tests/mod.rs
  core/lib/zksync_core/src/consistency_checker/tests/test_helpers.rs
Labels: external-contribution, validium

#148 feat: rename native (base) token address endpoint and return 0x0..01 with eth base token
  core/lib/web3_decl/src/namespaces/zks.rs
  core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs
  core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
Labels: external-contribution

#153 feat: Rollback `construct_pubdata` method.
  core/lib/types/src/commitment.rs
  core/lib/types/src/l1_batch_commit_data_generator.rs
  core/lib/types/src/utils.rs
Labels: external-contribution, validium

#155 Fix: native erc20 - rename test
  core/tests/ts-integration/tests/deposit-non-native-erc20.test.ts
Labels: bug, external-contribution

#161 fix: Remove `validium_mode_example` crate
  Cargo.lock
  Cargo.toml
  validium_mode_example/.gitignore
  validium_mode_example/BytesWriter.abi
  validium_mode_example/BytesWriter.bin
  validium_mode_example/BytesWriter.sol
  validium_mode_example/Cargo.toml
  validium_mode_example/Context.sol
  validium_mode_example/ERC20.abi
  validium_mode_example/ERC20.bin
  validium_mode_example/ERC20.sol
  validium_mode_example/Greeter.abi
  validium_mode_example/Greeter.bin
  validium_mode_example/Greeter.sol
  validium_mode_example/IERC20.sol
  validium_mode_example/IERC20Metadata.sol
  validium_mode_example/README.md
  validium_mode_example/src/main.rs
Labels: external-contribution, validium

#188 fix: Use `zksync_types::Bytes` instead of `Vec<u8>`
  core/lib/web3_decl/src/namespaces/zks.rs
  core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs
  core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
Labels: external-contribution, validium

#185 fix: Remove unused error
  core/lib/web3_decl/src/error.rs
  core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/mod.rs
Labels: external-contribution, validium
